version: '3'

services:

    base:
        container_name: sheng_ctf
        image: sheng_ctf:0.0
        ports:
          # ssh
          - "9453:22"
          # qira
          - "9487:3002"
        build:
          context: ./
        volumes:
          - ./ctf:/root/ctf
        privileged: true
        hostname: sheng_ctf
        restart: always
