version: '3'

services:

    base:
        container_name: sheng_ctf
        image: sheng_ctf:0.0
        ports:
          - "9453:22"
        build:
          context: ./
        privileged: true
        hostname: sheng_ctf
        restart: always
