#!/bin/bash
# Usage: network_settings [-d device_name] [-n private_address_segment]


dev=tun0
net=10.8.0.0
interface=$(ip route show default | grep default | awk '/.*/ {print $5}')


while getopts ":d:n:" args; do
    case $args in
        d)
            dev=$OPTARG
            ;;
        n)
            net=$OPTARG
            ;;
        \?)
            # echo "invalid option: -$OPTARG"
            # exit 1
            ;;
        :)
            # echo "Option -$OPTARG requires an argument."
            # exit 1
            ;;
    esac
done


echo ------------------------
echo setting up iptables

# IPv4 forward
sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
echo set "net.ipv4.ip_forward=1"

# iptables
iptables -t nat -A POSTROUTING -s ${net}/24 -o ${interface} -j MASQUERADE
echo iptables -t nat -A POSTROUTING -s ${net}/24 -o ${interface} -j MASQUERADE

iptables -A FORWARD -i ${dev} -j ACCEPT
echo iptables -A FORWARD -i ${dev} -j ACCEPT

iptables -A FORWARD -o ${dev} -j ACCEPT
echo iptables -A FORWARD -o ${dev} -j ACCEPT

echo ------------------------
echo Done!
